In [2]:
import torch
torch.__version__

'2.5.1+cu124'

In [ ]:
#scaler - zero dimension tensor
scaler = torch.tensor(7)
scaler

tensor(7)


In [ ]:
scaler.ndim # cheking the dimension of a tensor

0

In [ ]:
scaler.item() #converts torch.tensor to a python integer (only works with one element tensor)

7

In [ ]:
#vector
vector = torch.tensor([3,7])
vector

tensor([3, 7])

In [ ]:
vector.shape # tell how the elements are arranged on the inside

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[2,3],[5,6]]) #2-dimensional array of numbers
MATRIX

tensor([[2, 3],
        [5, 6]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[1,2,3], [3,4,5], [5,6,7]]) #n-dimensional array of numbers
TENSOR.shape

torch.Size([3, 3])

In [ ]:
random_tensor = torch.rand(1,3,3)
random_tensor, random_tensor.ndim, random_tensor.shape, random_tensor.dtype

(tensor([[[0.4438, 0.5902, 0.0911],
          [0.0580, 0.8697, 0.8777],
          [0.1321, 0.0457, 0.2793]]]),
 3,
 torch.Size([1, 3, 3]),
 torch.float32)

In [ ]:
zeros = torch.zeros(size=(2,2))
zeros

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
ones = torch.ones(size=(1,3,4))
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
zero_to_ten = torch.arange(1,9,1)
zero_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = torch.zeros_like(zero_to_ten)
x # similary can be done for one

tensor([0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# creating tensors with different datatype
float16_tensor = torch.tensor([3.0, 4.0,5.6], dtype=torch.half)
float16_tensor.dtype

torch.float16

In [ ]:
# basic operations on tensors
tensor = torch.tensor([1,2,3])
tensor + 10, tensor*10, tensor-10
# we can also use torch.mul, torch.add
# tensors valuse do not change until they have been resassigned

(tensor([11, 12, 13]), tensor([10, 20, 30]), tensor([-9, -8, -7]))

In [ ]:
a = torch.tensor([1,2,3])
b = torch.tensor([[3],[4],[5]])
torch.matmul(a,b)
# can also use '@' but not recommended
# matmul is faster compared to doing this via for loop
# can also use torch.mm which is short of matmul

tensor([26])

In [ ]:
# aggregation function
demo_tensor = torch.arange(0,100,10)
demo_tensor.min(), demo_tensor.max(), demo_tensor.sum(), demo_tensor.type(torch.float32).mean()
# mean() do not work without datatype and throws an error
#we can also use torch.max(demo_tensor)
#positional min and max
torch.argmin(demo_tensor)

tensor(0)

In [ ]:
# change tensor datatype
tensor = torch.tensor([21.4, 22.5, 56.7])
tensor = tensor.type(torch.float16)
tensor = tensor.type(torch.int8)
tensor.dtype, tensor

(torch.int8, tensor([21, 22, 56], dtype=torch.int8))

In [3]:
# reshaping, view, stacking, squeezing,
new_tensor = torch.arange(1,10)
new_tensor.shape

torch.Size([9])

In [6]:
new_tensor_reshaped = new_tensor.reshape(3,3)
new_tensor_reshaped.shape

torch.Size([3, 3])

In [10]:
view = new_tensor.view(1,3,3)
view, new_tensor
# changing the view, changes the tensor too

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [14]:
torch.stack([new_tensor, new_tensor], dim=0)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [21]:
new_tensor.squeeze()
new_tensor.unsqueeze(dim=1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [22]:
x = torch.randn(3,1,5)
x.shape

torch.Size([3, 1, 5])

In [26]:
y = torch.permute(x, (2,1,0)) # rearanges the dimensions in the specified order
y.size()

torch.Size([5, 1, 3])

In [28]:
import random
random_seed = 10
torch.manual_seed(seed=random_seed)
c = torch.rand(3,4)

torch.random.manual_seed(seed=random_seed)
d = torch.rand(3,4)
c,d

(tensor([[0.4581, 0.4829, 0.3125, 0.6150],
         [0.2139, 0.4118, 0.6938, 0.9693],
         [0.6178, 0.3304, 0.5479, 0.4440]]),
 tensor([[0.4581, 0.4829, 0.3125, 0.6150],
         [0.2139, 0.4118, 0.6938, 0.9693],
         [0.6178, 0.3304, 0.5479, 0.4440]]))